name: Build DockWatch DEB

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v6

      - name: Prepare package
        run: |
          VERSION="${GITHUB_REF_NAME#v}"
          PACKAGE_ROOT="packaging/build/dockwatch_${VERSION}"

          mkdir -p "$PACKAGE_ROOT/DEBIAN"
          mkdir -p "$PACKAGE_ROOT/usr/bin"

          cat > "$PACKAGE_ROOT/DEBIAN/control" <<EOF
          Package: dockwatch
          Version: ${VERSION}
          Section: utils
          Priority: optional
          Architecture: all
          Maintainer: Awnish Prasad <awnishprasad99@users.noreply.github.com>
          Description: Docker server monitoring CLI
           DockWatch monitors Docker containers, CPU, RAM, disk and Docker resources.
          EOF

          cp bin/dockwatch "$PACKAGE_ROOT/usr/bin/dockwatch"

          chmod 755 "$PACKAGE_ROOT/usr/bin/dockwatch"
          chmod 644 "$PACKAGE_ROOT/DEBIAN/control"

      - name: Build Debian package
        run: |
          VERSION="${GITHUB_REF_NAME#v}"

          dpkg-deb --build \
            "packaging/build/dockwatch_${VERSION}"

      - name: Check package
        run: |
          VERSION="${GITHUB_REF_NAME#v}"

          dpkg-deb --info \
            "packaging/build/dockwatch_${VERSION}.deb"

          dpkg-deb --contents \
            "packaging/build/dockwatch_${VERSION}.deb"

      - name: Upload DEB artifact
        uses: actions/upload-artifact@v4
        with:
          name: dockwatch-deb
          path: packaging/build/*.deb

      - name: Create GitHub Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          VERSION="${GITHUB_REF_NAME#v}"
          TAG="${GITHUB_REF_NAME}"

          gh release create "$TAG" \
            "packaging/build/dockwatch_${VERSION}.deb" \
            --title "DockWatch ${VERSION}" \
            --generate-notes
